version: "3.8"
services:
  reminder:
    image: reminder
    build:
      context: ./
    ports:
    - 3000:3000
    environment:
      MONGO_HOST: mongo
  mongo:
    image: mongo:4.4
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db
    - mongo_conf:/data/configdb
volumes:
  mongo_data:
  mongo_conf: