######################################################################
# Reminders
######################################################################

### Get reminders
GET http://localhost:8080/api/reminders

### Get reminder
GET http://localhost:8080/api/reminders/5fd365d6d0d2a232b90385d1

### Create reminder
POST http://localhost:8080/api/reminders
Content-Type: application/json

{
    "name": "TODO"
}

### Update reminder
PUT http://localhost:8080/api/reminders/5fd9054892e10637aea7861b
Content-Type: application/json

{
    "name": "TODO"
}

### Delete reminder
DELETE http://localhost:8080/api/reminders/5fd9054892e10637aea7861b

######################################################################
# Tasks
######################################################################

### Get tasks
GET http://localhost:8080/api/tasks

### Get task
GET http://localhost:8080/api/tasks/5fd9056092e10637aea7861c

### Get tasks by reminder
GET http://localhost:8080/api/reminders/5fda505501dd92002b744957/tasks

### Create task
POST http://localhost:8080/api/reminders/5fda505501dd92002b744957/tasks
Content-Type: application/json

{
    "name": "Faire ça",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
}

### Update task
PUT http://localhost:8080/api/reminders/5fd9054892e10637aea7861b/tasks/5fd9056092e10637aea7861c
Content-Type: application/json

{
    "name": "TODO",
    "description": "TODO stuff"
}

### Delete task
DELETE http://localhost:8080/api/tasks/5fd9056092e10637aea7861c

